### ISSUE TITLE
requirements.txt should be reviewed as the project does only work with pikepdf<=6.2.9

### ISSUE THREAD

**Issue by Max33260** [accessibility-luxembourg/simplA11yPDFCrawler#11]
Hello,

When first using this lib, I could not manage to make it work as I had the following error : 

`ImportError: cannot import name '_qpdf' from 'pikepdf' (/home/<user>/.local/lib/python3.10/site-packages/pikepdf/__init__.py)`

I found out that pikepdf should not be installed above 6.2.9

requirements.txt should be moved from

scrapy
pikepdf  
langcodes  
pdfminer.six  
bitstring  
dateparser  
typer

to

scrapy
pikepdf==6.2.9
langcodes
pdfminer.six
bitstring
dateparser
typer

**Comment by AlainVagner** [comment]
Hello, 
thank you for this issue. We will indeed need to update the requirements.
